### ISSUE TITLE
Reminder: Cryptodoc Update for Botan 3.5.0

### ISSUE THREAD

**Issue by FAlbertDev** [sehlen-bsi/botan-docs#214]
Reminder:
The following Cryptodoc sections must be updated for Botan 3.5.0:

- [x] Elliptic Curves 
- [x] X509 → (postponed until 3.6.0)
- [x] Kyber/Dilithium → @reneme
- [x] KDF sp800_56c (one-step/two-step) → @FAlbertDev → #223 
- [x] Security Issues (Audit Report) (postponed until CVEs are published) → @FAlbertDev

**Comment by reneme** [comment]
Done.
