### ISSUE TITLE
Audit of Botan 3.6.0 Patches

### ISSUE THREAD

**Issue by reneme** [sehlen-bsi/botan-docs#242]
We merged #230 prematurely to unblock other activities. Audit of many patches will come retrospectively in smaller PRs.

### TODO

| Category                      | Status                       | Assignee      |
| ----------------------------- | ---------------------------- | ------------- |
| `additions.yml`               | ✅     | @reneme       |
| `build_system.yml`            | :white_check_mark:           |               |
| `chore.yml`                   | :white_check_mark:           |               |
| `continuous_integration.yml`  | ✅     | @reneme       |
| `crystals.yml`                | ✅              | @FAlbertDev  |
| `ct_helpers.yml`              | ✅              | @FAlbertDev  |
| `documentation.yml`           | :white_check_mark:           |               |
| `encoding.yml`                | ✅               |  @FAlbertDev  |
| `fixes.yml`                   | ✅               |  @FAlbertDev  |
| `pcurves.yml`                 | ✅               |  @FAlbertDev             |
| `pqc.yml`                     | ✅               |  @FAlbertDev             |
| `release.yml`                 | ✅           | @reneme       |
| `tls.yml`                     | ✅               | @reneme        |
| `tpm2.yml`                    | ✅               |  @atreiber94    |
| `x509.yml`                    | ✅               | @reneme       |

🚧 - TODO
⏳  - In progress
👓- Ready for review 
✅  - Done

**Comment by FAlbertDev** [comment]
Done 🎉
